#!/bin/sh

enable_fanart=false

XMLTV_TYPE="WEB"
XMLTV_LOCATION_FILE=""
if [ "$enable_fanart" = true ]
then
    XMLTV_LOCATION_WEB="https://raw.githubusercontent.com/davidmuma/EPG_dobleM/master/guiafanart.xml.gz"
else
    XMLTV_LOCATION_WEB="https://raw.githubusercontent.com/davidmuma/EPG_dobleM/master/guiatv.xml.gz"
fi

dflag=
vflag=
cflag=

if [ $# -lt 1 ]; then

  if [ "$XMLTV_TYPE" = "FILE" ]; then

    
    cat "$XMLTV_LOCATION_FILE"
    exit 0

  elif [ "$XMLTV_TYPE" = "WEB" ]; then
    wget -qO - "$XMLTV_LOCATION_WEB" | zcat
    exit 0
  fi
fi

for arg
do
    delim=""
    case "$arg" in
    #translate --gnu-long-options to -g (short options)
       --description) args="${args}-d ";;
       --version) args="${args}-v ";;
       --capabilities) args="${args}-c ";;
       --quiet) args="${args}-q ";;

       #pass through anything else
       *) [[ "${arg:0:1}" == "-" ]] || delim="\""
           args="${args}${delim}${arg}${delim} ";;
    esac
done

#Reset the positional parameters to the short options
eval set -- $args

while getopts "dvcq" option
do
    case $option in
        d)  dflag=1;;
        v)  vflag=1;;
        c)  cflag=1;;
        q)  qflag=1;;
        \?) printf "unknown option: -%s\n" $OPTARG
            printf "Usage: %s: [--description] [--version] [--capabilities] \n" $(basename $0)
            exit 2
            ;;
    esac >&2
done

if [ "$dflag" ]
then
   printf "EPG_dobleM - Movistar+"
fi
if [ "$vflag" ]
then
   printf "0.2\n"
fi
if [ "$cflag" ]
then
   printf "baseline\n"
fi
if [ "$qflag" ]
then
   printf ""
fi

exit 0